services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "5000:5000"

  database:

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  db_data:
  portainer_data:
